export enum MessageEnum {
  UnAuthorized = 'No está autorizado',
  Online = 'Online',
  Offline = 'Offline',
  Active = 'Activo',
  Inactive = 'Inactivo',
  Disconnected = 'Desconectado',
  Connected = 'Conectado',
  Welcome = 'Bienvenido',
  GoodBye = 'Hasta luego',
  Successful = 'Exitoso',
  Completed = 'Completado',
  Incompleted = 'Incompleto',
  Error = 'Error',
  GenericError = 'Ha ocurrido un error inesperado',
}
