export enum RoutesEnum {
  Login = 'login',
  VerifyEmail = 'verify-email',
  Register = 'register',
  Logout = 'logout',
  Dashboard = 'dashboard',
  Landing = '',
  Home = '',
  AbuotUs = 'about-us',
  AdvisorPolicy = 'advisor-policy',
  Users = 'users',
  Advisors = 'advisors',
  Advisor = 'advisor',
  User = 'user',
  Details = 'details',
  Settings = 'settings',
  Chats = 'chats',
  RequestLogs = 'request-logs',
  Payments = 'payments',
  Categories = 'categories',
  Banks = 'banks',
  BanksAccounts = 'bank-accounts'
}
