export enum RoutesEnum {
  Login = 'login',
  VerifyEmail = 'verify-email',
  Register = 'auth/register',
  Logout = 'auth/logout',
  Dashboard = 'dashboard',
  Landing = '',
  Home = '',
  AbuotUs = 'about-us',
  AdvisorPolicy = 'advisor-policy',
  Users = 'users',
  Advisors = 'advisors',
  User = 'user',
  Details = 'details',
  Settings = 'settings',
  Chats = 'chats',
  RequestLogs = 'request-logs',
  Payments = 'payments',
  Categories = 'categories',
}
