export enum Api {
  TopRatedAdvisor = 'dashboard/top-rated-advisors',
  NewRegistrations = 'dashboard/new-registrations',
  Settings = 'settings',
  Login = 'auth/sign-in',
  Logout = 'auth/sign-out',
  Register = 'auth/sign-up',
  ForgotPassword = 'auth/forgot-password',
  ResetPassword = 'auth/reset-password',
  Menu = 'web-menu',
  Users = 'users',
  UserSummary = 'dashboard/users/summary',
  Payments = 'payments',
  Rooms = 'chat/rooms',
  Messages = 'chat/messages',
  UsersTotals = 'users/dashboard-totals-cards',
  RequestLogs = 'request-logs/group-by/asesor',
  SummaryStatus = 'request-logs/summary/status',
  SummaryMonthlyByYear = 'request-logs/summary/monthly-status',
  Categories = 'categories',
  CategoriesNoParams = 'categories/no-params',
}

